### ISSUE TITLE
Feature request: Configure tick cleaner to keep oldest send for single pitch routes

### ISSUE THREAD

**Issue by jdmoorman** [derat/mpticks#4]
When I climb the same single-pitch sport route multiple times in one day, I log the laps as a single tick with multiple pitches. These ticks are much less significant than the very first tick. Thus, rather than opting to keep the tick with the most pitches, it would be preferable to keep the oldest tick for such situations.

As an alternative, if we can leverage the data from mpticks.app.com, we can check the number of pitches for each route take the oldest tick with the most number of pitches up to the length of the route.

**Comment by derat** [comment]
It's been a while since I've thought about this code, but I'm pretty sure I remember seeing routes with incorrect pitch counts in MP. I think I documented this for myself at https://github.com/derat/mpticks/blob/master/src/api.ts#L19 -- if the pitch count is unset, the API apparently returns 1. This seems like it makes it impossible to distinguish between these two cases:

- a three-pitch route has an unset pitch count in MP
- someone climbs the first pitch and bails, recording a one-pitch tick
- they come back later and climb all three pitches, recording a three-pitch tick

- a single-pitch route (correctly) has a pitch count of 1 in MP
- someone climbs the route and records a one-pitch tick
- they come back later and record three laps as a three-pitch tick

In the first case, it'd probably be desirable to preserve the second tick, while in the first case, the first tick should be preserved. From the extension's perspective, I think that these cases look identical, though: the API reports that the route has one pitch, and there's an earlier tick with one pitch and a later tick with three pitches. This is too bad, because the extension is already getting the pitch counts from MP -- it calls the API so it can display route names.

It looks like I decided to rank ticks by descending pitches and then style. I suppose that ranking by style first and then pitches would be an option as well -- that would preserve onsights of single-pitch routes, at least.

Let me know if you can think of some way to automatically do the right thing here. Maybe the missing-pitch-count case isn't worth worrying about. I'm pretty sure I only saw it for single-pitch routes, so it might not really matter that the API defaults to returning 1.

**Comment by derat** [comment]
Whoops, the comment I quoted was referring to the API call for getting ticks, not routes. I think I can detect when a route's tick count is missing. Let me try hacking together a change to improve the logic here.

**Comment by derat** [comment]
I think that ada680c18fede4630b71769829e5191a3582dc52 should handle this, if you want to give it a try (i.e. download it, go to `chrome://extensions`, `Developer mode`, `Load unpacked`, browse to the repo's `chrome/` directory).
